### ISSUE TITLE
Permitir que los registros se actualicen al vuelo

### ISSUE THREAD

**Issue by basicavisual** [ixmael/acapulco-sos#3]
Si agrego un nuevo dato, no se ve reflejado en el front-end, requiere un refresh. En palabras de @ixmael `Si no se actualiza habría que ejecutar esto curl -X POST https://acapulco-sos.irm.mx/__refresh `

Creo que habría que implementar SSR:
https://www.gatsbyjs.com/docs/how-to/rendering-options/using-server-side-rendering/

También estamos abiertas  a usar otra cosa que no sea Gatsby. Bienvenida la discusión / PRs

**Comment by diegoaguilar** [comment]
Para nuevos registros pueden crear un webbhook en contentful que llame a ese endpoint 

Pueden filtrar por evento y content type

**Comment by diegoaguilar** [comment]
Si el evento es published, nuevos registros y los cambios harían el refresh

**Comment by categulario** [comment]
resuelto. Feo, pero está resuelto
